### ISSUE TITLE
Upstream for Debian?

### ISSUE THREAD

**Issue by Zugschlus** [wilx/apg#3]
Hi,

I am the maintainer of apg in Debian. How much commitment do you have for your fork of apg? Would you be okay with the Debian package switching to your release as the upstream?

Greetings
Marc

**Comment by wilx** [comment]
I have not touched it for 10 years. I only made it work for me when I needed it at some point. I doubt there is much benefit for Debian to switch to this fork, unless you need the Autoconf/Automake build system.

**Comment by Zugschlus** [comment]
Thanks for the information. I still appreciate your work!
